SAMPLES = ['Sample1', 'Sample2']

rule all:
    input:
        expand('results/{sample}.txt', sample = SAMPLES)

rule quantify_genes:
    input:
        genome = 'snakemake-test/data/genome.fa',
        r1 = 'snakemake-test/data/{sample}.R1.fastq.gz',
        r2 = 'snakemake-test/data/{sample}.R2.fastq.gz'
    output:
        'results/{sample}.txt'
    shell:
        'echo {input.genome} {input.r1} {input.r2} > {output}'

rule clean:
    shell:
        'rm *.txt'