url = "bioinf.nl/~fennaf/snakemake/WC03/data/"
SAMPLES = [x for x in 'ABDEFGHIJ']

rule all:
    input:
       expand("{sample}.bam", sample=SAMPLES)

rule download:
    output:
       "{sample}.bam"
    shell:
        "wget {url}{output}"
